export interface ReconciliationRecord {
  id: number;
  auctionHouse: string;
  account: string;
  total: number;
  payments: number;
  status: "Matched" | "Unmatched";
}

export const auctionHouses = [
  "Woxholt Auktioner",
  "Palsgaard Kunstauktioner",
  "Stockholms Auktionsverk Helsinki",
  "Arce Auctions",
  "Barcelona Auctions",
  "Balclis",
  "Lawrences Auctioneers",
  "Lots Road Auctions",
  "Acreman St Auctioneers & Valuers",
  "Rumsey's Auctioneers",
  "Chalkwell Auctions",
  "Bishop & Miller",
  "Borås Auktionshall",
  "Sajab Vintage",
  "Gästriklands Auktionskammare",
  "Scandinavian Music & Design Auctions",
  "Stockholms Auktionsverk Göteborg",
  "Connoisseur Bokauktioner",
  "Göteborgs Auktionsverk",
  "Halmstads Auktionskammare",
  "Tisas",
  "Stockholms Auktionsverk Helsingborg",
  "Helsingborgs Auktionskammare",
  "Auktionshuset STO Bohuslän",
  "Hälsinglands Auktionsverk",
  "Höganäs Auktionsverk",
  "Höörs Auktionshall",
  "Gomér & Andersson Jönköping",
  "Auktionskammaren Sydost Kalmar",
  "Auktionsfirma Kenneth Svensson i Kalmar",
  "Kalmar Auktionsverk",
  "Ekenbergs",
  "Karlstad Hammarö Auktionsverk",
  "Södermanlands Auktionsverk",
  "Laholms Auktionskammare",
  "Skånes Auktionsverk",
  "Gomér & Andersson Linköping",
  "Björnssons Auktionskammare",
  "Crafoord Auktioner Lund",
  "Lysekils Auktionsbyrå",
  "Limhamns Auktionsbyrå",
  "Crafoord Auktioner Malmö",
  "Stockholms Auktionsverk Malmö",
  "Garpenhus Auktioner",
  "Toka Auktionshus",
  "Auktionshuset Thörner & Ek",
  "Gomér & Andersson Norrköping",
  "RA Auktionsverket Norrköping",
  "Roslagens Auktionsverk",
  "Gomér & Andersson Nyköping",
  "Auktionshuset Thelin & Johansson",
  "Handelslagret Auktionsservice",
  "Formstad Auktioner",
  "Stockholms Auktionsverk Sickla",
  "Stockholms Auktionsverk Magasin 5",
  "Stockholms Auktionsverk Fine Art",
  "Crafoord Auktioner Stockholm",
  "Walter Borg",
  "Mauritz Widforss",
  "Auktionshuset Kolonn",
  "Stadsauktion Sundsvall",
  "Markus Auktioner",
  "Norrlands Auktionsverk",
  "Varberg Auktionskammare",
  "Auktionsmagasinet Vänersborg",
  "Växjö Auktionskammare",
  "Auktionsverket Engelholm",
  "Örebro Stadsauktioner",
  "Auction Now",
  "Auktionshaus Bossard",
  "Stockholms Auktionsverk Düsseldorf/Neuss",
  "Auktionshaus Blank",
  "Stockholms Auktionsverk Hamburg",
  "Colombos",
  "HannoVerum",
  "Stockholms Auktionsverk Köln",
  "Auktionshaus Stuber's Hammerschlag",
  "Kunst- und Auktionshaus Kleinhenz"
];

export const accountNumbers = ["10001", "10002", "10003", "10004", "10005"];
export const statusOptions = ["All", "Matched", "Unmatched"];
